package com.zy.SmartCampus.polo;


import lombok.Data;

import java.util.List;

@Data
public class ZigBeeGatewayDevInfo extends ZigBeeGatewayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.id
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.dev_id
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.zigBee_id
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String zigbeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.ep
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String ep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.did
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.dtype
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String dtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.ol
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String ol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.on
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.dn
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String dn;

   private  String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.school
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.house
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String house;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.floor
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_info_zigbee.room
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String room;


    public ZigBeeGatewayDevStatus st;


    public List<ZigBeeGatewayDevInfo> devInfoEps; //多路开关信息

    @Data
    public static class ZigBeeGatewayDevStatus {
        private String on;//开关状态:true：开false：关
        private String eplist;//设备所有端口的列表，例如设备有 1、2、3 端 口 ， eplist 为“0010002003”，端口列表没有顺序，也可以 为“002001003”
        private String dsp;////厂商对设备的描述
        private String ztype;////zone 设备类型
        private String ps;//电源类型
        private String wmode;//空调模式
        private String pt;//窗帘开度
        private String swid;//软件ID，软件版本号
        private String mlux;//测量光照度
        private String zsta;//zone 设备状态
        private String mhumi;//测量湿度
        private String mtemp;//测量温度
        private String inle;//红外码
        private String indsp;//红外码库信息
        private String inct;//红外控制命令
        private String cts;//电机操作---0：关，向下，反转等；1：开，向上，正转等；2：停止//工作模式---3：正转；4：反转//  9：设置边界  ；10：取消边界

        @Override
        public String toString() {
            return "ZigBeeGatewayDevStatus{" +
                    "on='" + on + '\'' +
                    ", eplist='" + eplist + '\'' +
                    ", dsp='" + dsp + '\'' +
                    ", ztype='" + ztype + '\'' +
                    ", ps='" + ps + '\'' +
                    ", wmode='" + wmode + '\'' +
                    ", pt='" + pt + '\'' +
                    ", swid='" + swid + '\'' +
                    ", mlux='" + mlux + '\'' +
                    ", zsta='" + zsta + '\'' +
                    ", mhumi='" + mhumi + '\'' +
                    ", mtemp='" + mtemp + '\'' +
                    ", inle='" + inle + '\'' +
                    ", indsp='" + indsp + '\'' +
                    ", inct='" + inct + '\'' +
                    ", cts='" + cts + '\'' +
                    '}';
        }
    }

    @Override
    public String toString() {
        return "ZigBeeGatewayDevInfo{" +
                "id='" + id + '\'' +
                ", devId='" + devId + '\'' +
                ", zigbeeId='" + zigbeeId + '\'' +
                ", ep='" + ep + '\'' +
                ", did='" + did + '\'' +
                ", dtype='" + dtype + '\'' +
                ", ol='" + ol + '\'' +
                ", dn='" + dn + '\'' +
                ", note='" + note + '\'' +
                ", school='" + school + '\'' +
                ", house='" + house + '\'' +
                ", floor='" + floor + '\'' +
                ", room='" + room + '\'' +
                ", st=" + st +
                ", devInfoEps=" + devInfoEps +
                '}';
    }
}