package com.zy.SmartCampus.polo;

import lombok.Data;

@Data
public class ZigBeeGatewayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.id
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.zigBee_id
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String zigbeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.mac
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.ol
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String ol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.gwver
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String gwver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.gwtype
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String gwtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.gwmoder
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String gwmoder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.nettype
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String nettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.school
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.house
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String house;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.floor
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zigbee_info.room
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    private String room;

    private String remark;

    private String state;

    private int devCount;  //设备数量
    private int devOnlineCount; //设备在线数量
    private int devOfflineCount; //设备离线数量





}