package com.zy.SmartCampus.mapper;

import com.alibaba.fastjson.JSONObject;
import com.zy.SmartCampus.polo.ZigBeeGatewayDevInfo;

import java.util.List;

public interface ZigBeeGatewayDevInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_info_zigbee
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int deleteByPrimaryKey(String zigbeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_info_zigbee
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int insert(ZigBeeGatewayDevInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_info_zigbee
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int insertSelective(ZigBeeGatewayDevInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_info_zigbee
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    List<ZigBeeGatewayDevInfo> selectByPrimaryKey(ZigBeeGatewayDevInfo zigBeeGatewayDevInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_info_zigbee
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int updateByPrimaryKeySelective(ZigBeeGatewayDevInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_info_zigbee
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int updateByPrimaryKey(ZigBeeGatewayDevInfo record);

    List<ZigBeeGatewayDevInfo> selectZigBeeDevInfoByJSON(JSONObject jsonObject);
}