package com.zy.SmartCampus.mapper;

import com.alibaba.fastjson.JSONObject;
import com.zy.SmartCampus.polo.ZigBeeGatewayInfo;

import java.util.List;

public interface ZigBeeGatewayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zigbee_info
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int deleteByPrimaryKey(String zigbeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zigbee_info
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int insert(ZigBeeGatewayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zigbee_info
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int insertSelective(ZigBeeGatewayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zigbee_info
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    ZigBeeGatewayInfo selectByPrimaryKey(String zigbeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zigbee_info
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int updateByPrimaryKeySelective(ZigBeeGatewayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zigbee_info
     *
     * @mbg.generated Wed Jul 28 16:44:15 CST 2021
     */
    int updateByPrimaryKey(ZigBeeGatewayInfo record);

    List<ZigBeeGatewayInfo> selectZigBeeInfoByJsonObject(JSONObject jsonObject);
}